CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL, -- aqui armazena o hash bcrypt
  data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP
);